runtime: python38

instance_class: F2

env_variables:
        MY_CUSTOM_ENV_VAR: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/golden-retriever-royalty-free-image-506756303-1560962726.jpg?crop=0.672xw:1.00xh;0.166xw,0&resize=640:*"


